name: Deploy to Cloud Run
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}
          service_account: ${{ secrets.GCP_SA_ID }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker authentication
        run: gcloud auth configure-docker --quiet

      - name: Build and Push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/tree-of-thrones-image:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/tree-of-thrones-image:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/tree-of-thrones-image:latest
          service: tree-of-thrones-service
          region: ${{ secrets.GCP_REGION }}